import {
  Accessibility,
  Activity,
  AlertCircle,
  Archive,
  ArrowRight,
  Ban,
  Bell,
  BookOpen,
  Building2,
  Calendar,
  CalendarCheck,
  Check,
  ChevronDown,
  ChevronRight,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Compass,
  CreditCard,
  Ear,
  Eye,
  EyeOff,
  FileText,
  Flag,
  Gauge,
  Gift,
  Globe,
  Hand,
  HandHeart,
  Headphones,
  Heart,
  HeartHandshake,
  HelpCircle,
  Home,
  Image,
  ImagePlus,
  Images,
  LayoutDashboard,
  Languages,
  LifeBuoy,
  Link2,
  List,
  Lock,
  MapPin,
  Menu,
  MessageCircle,
  MessageSquare,
  MessagesSquare,
  Mic,
  MicOff,
  Moon,
  Music,
  Pause,
  Phone,
  PhoneCall,
  Plane,
  Play,
  Plug,
  Puzzle,
  Quote,
  Search,
  Settings2,
  SkipBack,
  SkipForward,
  Navigation,
  Share2,
  Shield,
  ShieldAlert,
  ShieldCheck,
  SlidersHorizontal,
  Sparkles,
  Star,
  Stethoscope,
  Sun,
  Sunrise,
  Timer,
  TrendingUp,
  Type,
  User,
  UserCheck,
  Users,
  Volume2,
  Wind,
  X,
  type LucideIcon,
} from "lucide-react";

/**
 * Curated icon registry.
 *
 * Content modules reference icons by kebab-case name, which keeps the data
 * layer free of React imports and CMS-ready. Explicit imports (rather than
 * `import * as`) keep the bundle tree-shakeable — an unresolved name falls
 * back to a neutral mark rather than throwing.
 */
const REGISTRY: Record<string, LucideIcon> = {
  accessibility: Accessibility,
  activity: Activity,
  "alert-circle": AlertCircle,
  archive: Archive,
  "arrow-right": ArrowRight,
  "audio-lines": Volume2,
  ban: Ban,
  bell: Bell,
  "book-open": BookOpen,
  "building-2": Building2,
  calendar: Calendar,
  "calendar-check": CalendarCheck,
  check: Check,
  "chevron-down": ChevronDown,
  "chevron-right": ChevronRight,
  "circle-help": HelpCircle,
  "clipboard-check": ClipboardCheck,
  "clipboard-list": ClipboardList,
  clock: Clock,
  compass: Compass,
  contrast: Sun,
  "credit-card": CreditCard,
  ear: Ear,
  eye: Eye,
  "eye-off": EyeOff,
  "file-text": FileText,
  flag: Flag,
  gauge: Gauge,
  gift: Gift,
  "git-branch": Share2,
  globe: Globe,
  hand: Hand,
  "hand-heart": HandHeart,
  headphones: Headphones,
  heart: Heart,
  "heart-handshake": HeartHandshake,
  home: Home,
  image: Image,
  "image-plus": ImagePlus,
  images: Images,
  languages: Languages,
  "layout-dashboard": LayoutDashboard,
  "life-buoy": LifeBuoy,
  link: Link2,
  list: List,
  lock: Lock,
  "map-pin": MapPin,
  menu: Menu,
  "message-circle": MessageCircle,
  "message-square-off": MessageSquare,
  "messages-square": MessagesSquare,
  mic: Mic,
  "mic-off": MicOff,
  "mic-vocal": Mic,
  moon: Moon,
  music: Music,
  pause: Pause,
  phone: Phone,
  "phone-call": PhoneCall,
  plane: Plane,
  play: Play,
  plug: Plug,
  pointer: Hand,
  puzzle: Puzzle,
  quote: Quote,
  search: Search,
  "settings-2": Settings2,
  "skip-back": SkipBack,
  "skip-forward": SkipForward,
  navigation: Navigation,
  "share-2": Share2,
  shield: Shield,
  "shield-alert": ShieldAlert,
  "shield-check": ShieldCheck,
  "sliders-horizontal": SlidersHorizontal,
  sparkles: Sparkles,
  star: Star,
  stethoscope: Stethoscope,
  sun: Sun,
  sunrise: Sunrise,
  timer: Timer,
  "trending-up": TrendingUp,
  type: Type,
  user: User,
  "user-check": UserCheck,
  users: Users,
  "volume-2": Volume2,
  wind: Wind,
  x: X,
};

export function resolveIcon(name: string): LucideIcon {
  return REGISTRY[name] ?? Sparkles;
}

export function Icon({
  name,
  className,
  strokeWidth = 1.75,
}: {
  name: string;
  className?: string;
  strokeWidth?: number;
}) {
  const Component = resolveIcon(name);
  return <Component className={className} strokeWidth={strokeWidth} aria-hidden="true" />;
}

export default Icon;
