/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as DayInTheLifeRouteImport } from './routes/day-in-the-life'
import { Route as FamiliesRouteImport } from './routes/families'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as GetStartedRouteImport } from './routes/get-started'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as LanguagesRouteImport } from './routes/languages'
import { Route as MemoriesRouteImport } from './routes/memories'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as ScenariosRouteImport } from './routes/scenarios'
import { Route as SeniorsRouteImport } from './routes/seniors'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AdventuresIndexRouteImport } from './routes/adventures.index'
import { Route as AdventuresSlugRouteImport } from './routes/adventures.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const DayInTheLifeRoute = DayInTheLifeRouteImport.update({
  id: '/day-in-the-life',
  path: '/day-in-the-life',
  getParentRoute: () => rootRouteImport,
} as any)
const FamiliesRoute = FamiliesRouteImport.update({
  id: '/families',
  path: '/families',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const GetStartedRoute = GetStartedRouteImport.update({
  id: '/get-started',
  path: '/get-started',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const LanguagesRoute = LanguagesRouteImport.update({
  id: '/languages',
  path: '/languages',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoriesRoute = MemoriesRouteImport.update({
  id: '/memories',
  path: '/memories',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenariosRoute = ScenariosRouteImport.update({
  id: '/scenarios',
  path: '/scenarios',
  getParentRoute: () => rootRouteImport,
} as any)
const SeniorsRoute = SeniorsRouteImport.update({
  id: '/seniors',
  path: '/seniors',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdventuresIndexRoute = AdventuresIndexRouteImport.update({
  id: '/adventures/',
  path: '/adventures/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdventuresSlugRoute = AdventuresSlugRouteImport.update({
  id: '/adventures/$slug',
  path: '/adventures/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/day-in-the-life': typeof DayInTheLifeRoute
  '/families': typeof FamiliesRoute
  '/faq': typeof FaqRoute
  '/get-started': typeof GetStartedRoute
  '/how-it-works': typeof HowItWorksRoute
  '/languages': typeof LanguagesRoute
  '/memories': typeof MemoriesRoute
  '/partners': typeof PartnersRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRoute
  '/safety': typeof SafetyRoute
  '/scenarios': typeof ScenariosRoute
  '/seniors': typeof SeniorsRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/adventures/$slug': typeof AdventuresSlugRoute
  '/adventures/': typeof AdventuresIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/day-in-the-life': typeof DayInTheLifeRoute
  '/families': typeof FamiliesRoute
  '/faq': typeof FaqRoute
  '/get-started': typeof GetStartedRoute
  '/how-it-works': typeof HowItWorksRoute
  '/languages': typeof LanguagesRoute
  '/memories': typeof MemoriesRoute
  '/partners': typeof PartnersRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRoute
  '/safety': typeof SafetyRoute
  '/scenarios': typeof ScenariosRoute
  '/seniors': typeof SeniorsRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/adventures/$slug': typeof AdventuresSlugRoute
  '/adventures': typeof AdventuresIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/day-in-the-life': typeof DayInTheLifeRoute
  '/families': typeof FamiliesRoute
  '/faq': typeof FaqRoute
  '/get-started': typeof GetStartedRoute
  '/how-it-works': typeof HowItWorksRoute
  '/languages': typeof LanguagesRoute
  '/memories': typeof MemoriesRoute
  '/partners': typeof PartnersRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRoute
  '/safety': typeof SafetyRoute
  '/scenarios': typeof ScenariosRoute
  '/seniors': typeof SeniorsRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/adventures/$slug': typeof AdventuresSlugRoute
  '/adventures/': typeof AdventuresIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accessibility'
    | '/day-in-the-life'
    | '/families'
    | '/faq'
    | '/get-started'
    | '/how-it-works'
    | '/languages'
    | '/memories'
    | '/partners'
    | '/privacy'
    | '/resources'
    | '/safety'
    | '/scenarios'
    | '/seniors'
    | '/support'
    | '/terms'
    | '/adventures/$slug'
    | '/adventures/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accessibility'
    | '/day-in-the-life'
    | '/families'
    | '/faq'
    | '/get-started'
    | '/how-it-works'
    | '/languages'
    | '/memories'
    | '/partners'
    | '/privacy'
    | '/resources'
    | '/safety'
    | '/scenarios'
    | '/seniors'
    | '/support'
    | '/terms'
    | '/adventures/$slug'
    | '/adventures'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/accessibility'
    | '/day-in-the-life'
    | '/families'
    | '/faq'
    | '/get-started'
    | '/how-it-works'
    | '/languages'
    | '/memories'
    | '/partners'
    | '/privacy'
    | '/resources'
    | '/safety'
    | '/scenarios'
    | '/seniors'
    | '/support'
    | '/terms'
    | '/adventures/$slug'
    | '/adventures/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccessibilityRoute: typeof AccessibilityRoute
  DayInTheLifeRoute: typeof DayInTheLifeRoute
  FamiliesRoute: typeof FamiliesRoute
  FaqRoute: typeof FaqRoute
  GetStartedRoute: typeof GetStartedRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LanguagesRoute: typeof LanguagesRoute
  MemoriesRoute: typeof MemoriesRoute
  PartnersRoute: typeof PartnersRoute
  PrivacyRoute: typeof PrivacyRoute
  ResourcesRoute: typeof ResourcesRoute
  SafetyRoute: typeof SafetyRoute
  ScenariosRoute: typeof ScenariosRoute
  SeniorsRoute: typeof SeniorsRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  AdventuresSlugRoute: typeof AdventuresSlugRoute
  AdventuresIndexRoute: typeof AdventuresIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/day-in-the-life': {
      id: '/day-in-the-life'
      path: '/day-in-the-life'
      fullPath: '/day-in-the-life'
      preLoaderRoute: typeof DayInTheLifeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/families': {
      id: '/families'
      path: '/families'
      fullPath: '/families'
      preLoaderRoute: typeof FamiliesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-started': {
      id: '/get-started'
      path: '/get-started'
      fullPath: '/get-started'
      preLoaderRoute: typeof GetStartedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/languages': {
      id: '/languages'
      path: '/languages'
      fullPath: '/languages'
      preLoaderRoute: typeof LanguagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memories': {
      id: '/memories'
      path: '/memories'
      fullPath: '/memories'
      preLoaderRoute: typeof MemoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenarios': {
      id: '/scenarios'
      path: '/scenarios'
      fullPath: '/scenarios'
      preLoaderRoute: typeof ScenariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seniors': {
      id: '/seniors'
      path: '/seniors'
      fullPath: '/seniors'
      preLoaderRoute: typeof SeniorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adventures/': {
      id: '/adventures/'
      path: '/adventures'
      fullPath: '/adventures/'
      preLoaderRoute: typeof AdventuresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adventures/$slug': {
      id: '/adventures/$slug'
      path: '/adventures/$slug'
      fullPath: '/adventures/$slug'
      preLoaderRoute: typeof AdventuresSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccessibilityRoute: AccessibilityRoute,
  DayInTheLifeRoute: DayInTheLifeRoute,
  FamiliesRoute: FamiliesRoute,
  FaqRoute: FaqRoute,
  GetStartedRoute: GetStartedRoute,
  HowItWorksRoute: HowItWorksRoute,
  LanguagesRoute: LanguagesRoute,
  MemoriesRoute: MemoriesRoute,
  PartnersRoute: PartnersRoute,
  PrivacyRoute: PrivacyRoute,
  ResourcesRoute: ResourcesRoute,
  SafetyRoute: SafetyRoute,
  ScenariosRoute: ScenariosRoute,
  SeniorsRoute: SeniorsRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  AdventuresSlugRoute: AdventuresSlugRoute,
  AdventuresIndexRoute: AdventuresIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
