/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BuildRouteImport } from './routes/build'
import { Route as BusyworkRouteImport } from './routes/busywork'
import { Route as ChallengeRouteImport } from './routes/challenge'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CreateRouteImport } from './routes/create'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as IdeasRouteImport } from './routes/ideas'
import { Route as InspireRouteImport } from './routes/inspire'
import { Route as LessonsRouteImport } from './routes/lessons'
import { Route as MaterialsRouteImport } from './routes/materials'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as RecentWorkRouteImport } from './routes/recent-work'
import { Route as WorkspaceRouteImport } from './routes/workspace'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildRoute = BuildRouteImport.update({
  id: '/build',
  path: '/build',
  getParentRoute: () => rootRouteImport,
} as any)
const BusyworkRoute = BusyworkRouteImport.update({
  id: '/busywork',
  path: '/busywork',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengeRoute = ChallengeRouteImport.update({
  id: '/challenge',
  path: '/challenge',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeasRoute = IdeasRouteImport.update({
  id: '/ideas',
  path: '/ideas',
  getParentRoute: () => rootRouteImport,
} as any)
const InspireRoute = InspireRouteImport.update({
  id: '/inspire',
  path: '/inspire',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsRoute = LessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialsRoute = MaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const RecentWorkRoute = RecentWorkRouteImport.update({
  id: '/recent-work',
  path: '/recent-work',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/build': typeof BuildRoute
  '/busywork': typeof BusyworkRoute
  '/challenge': typeof ChallengeRoute
  '/contact': typeof ContactRoute
  '/create': typeof CreateRoute
  '/gallery': typeof GalleryRoute
  '/ideas': typeof IdeasRoute
  '/inspire': typeof InspireRoute
  '/lessons': typeof LessonsRoute
  '/materials': typeof MaterialsRoute
  '/packages': typeof PackagesRoute
  '/recent-work': typeof RecentWorkRoute
  '/workspace': typeof WorkspaceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/build': typeof BuildRoute
  '/busywork': typeof BusyworkRoute
  '/challenge': typeof ChallengeRoute
  '/contact': typeof ContactRoute
  '/create': typeof CreateRoute
  '/gallery': typeof GalleryRoute
  '/ideas': typeof IdeasRoute
  '/inspire': typeof InspireRoute
  '/lessons': typeof LessonsRoute
  '/materials': typeof MaterialsRoute
  '/packages': typeof PackagesRoute
  '/recent-work': typeof RecentWorkRoute
  '/workspace': typeof WorkspaceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/build': typeof BuildRoute
  '/busywork': typeof BusyworkRoute
  '/challenge': typeof ChallengeRoute
  '/contact': typeof ContactRoute
  '/create': typeof CreateRoute
  '/gallery': typeof GalleryRoute
  '/ideas': typeof IdeasRoute
  '/inspire': typeof InspireRoute
  '/lessons': typeof LessonsRoute
  '/materials': typeof MaterialsRoute
  '/packages': typeof PackagesRoute
  '/recent-work': typeof RecentWorkRoute
  '/workspace': typeof WorkspaceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/build'
    | '/busywork'
    | '/challenge'
    | '/contact'
    | '/create'
    | '/gallery'
    | '/ideas'
    | '/inspire'
    | '/lessons'
    | '/materials'
    | '/packages'
    | '/recent-work'
    | '/workspace'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/build'
    | '/busywork'
    | '/challenge'
    | '/contact'
    | '/create'
    | '/gallery'
    | '/ideas'
    | '/inspire'
    | '/lessons'
    | '/materials'
    | '/packages'
    | '/recent-work'
    | '/workspace'
  id:
    | '__root__'
    | '/'
    | '/build'
    | '/busywork'
    | '/challenge'
    | '/contact'
    | '/create'
    | '/gallery'
    | '/ideas'
    | '/inspire'
    | '/lessons'
    | '/materials'
    | '/packages'
    | '/recent-work'
    | '/workspace'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuildRoute: typeof BuildRoute
  BusyworkRoute: typeof BusyworkRoute
  ChallengeRoute: typeof ChallengeRoute
  ContactRoute: typeof ContactRoute
  CreateRoute: typeof CreateRoute
  GalleryRoute: typeof GalleryRoute
  IdeasRoute: typeof IdeasRoute
  InspireRoute: typeof InspireRoute
  LessonsRoute: typeof LessonsRoute
  MaterialsRoute: typeof MaterialsRoute
  PackagesRoute: typeof PackagesRoute
  RecentWorkRoute: typeof RecentWorkRoute
  WorkspaceRoute: typeof WorkspaceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build': {
      id: '/build'
      path: '/build'
      fullPath: '/build'
      preLoaderRoute: typeof BuildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/busywork': {
      id: '/busywork'
      path: '/busywork'
      fullPath: '/busywork'
      preLoaderRoute: typeof BusyworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenge': {
      id: '/challenge'
      path: '/challenge'
      fullPath: '/challenge'
      preLoaderRoute: typeof ChallengeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ideas': {
      id: '/ideas'
      path: '/ideas'
      fullPath: '/ideas'
      preLoaderRoute: typeof IdeasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspire': {
      id: '/inspire'
      path: '/inspire'
      fullPath: '/inspire'
      preLoaderRoute: typeof InspireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons': {
      id: '/lessons'
      path: '/lessons'
      fullPath: '/lessons'
      preLoaderRoute: typeof LessonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materials': {
      id: '/materials'
      path: '/materials'
      fullPath: '/materials'
      preLoaderRoute: typeof MaterialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recent-work': {
      id: '/recent-work'
      path: '/recent-work'
      fullPath: '/recent-work'
      preLoaderRoute: typeof RecentWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuildRoute: BuildRoute,
  BusyworkRoute: BusyworkRoute,
  ChallengeRoute: ChallengeRoute,
  ContactRoute: ContactRoute,
  CreateRoute: CreateRoute,
  GalleryRoute: GalleryRoute,
  IdeasRoute: IdeasRoute,
  InspireRoute: InspireRoute,
  LessonsRoute: LessonsRoute,
  MaterialsRoute: MaterialsRoute,
  PackagesRoute: PackagesRoute,
  RecentWorkRoute: RecentWorkRoute,
  WorkspaceRoute: WorkspaceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
